/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import TodoApp.controller.ProjectController;
import TodoApp.controller.TaskController;
import TodoApp.model.Project;
import TodoApp.model.Task;
import java.util.Date;
import java.util.List;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

//        ProjectController projectController = new ProjectController();

//        Project project = new Project();
//        project.setName("Projeto Three");
//        project.setDescription("Sem esforço, sem vitória");
//        projectController.save(project);
//        
//        project.setId(2);
//        project.setName("Novo nome do projeto");
//        projectController.update(project);
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos = " + projects.size());
//        projectController.removeById(3);

        
//        TaskController taskController = new TaskController();
//        
//        Task task = new Task();
//        task.setIdProject(1);
//        task.setName("Teste Atualização");
//        task.setDescription("Somente testando");
//        task.setNotes("S Notas");
//        task.setCompleted(false);
//        task.setDeadline(new Date());
        
//        taskController.save(task);
        
//        task.setId(3);
//        String novoNome = "Alterar telas da aplicação";
//        task.setName(novoNome);
//        taskController.update(task);
//        
//        List<Task> tasks = taskController.getAll(1);
//        System.out.println("Total de tarefas = " + tasks.size());
//        
//        
//        System.out.println("Tarefas do projeto do id 1 - Carreiras Policiais");
//        tasks.forEach((t) -> {
//            System.out.println(t);
//        });
    }
}
