/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp.main;

import TodoApp.controller.ProjectDAO;
import TodoApp.controller.TaskDAO;
import TodoApp.model.Project;
import TodoApp.model.Task;
import java.util.Date;
import java.util.List;

public class Main {
    
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        ProjectDAO projectController = new ProjectDAO();

//        Project project = new Project();
//        project.setName("Projeto Three");
//        project.setDescription("Sem esforço, sem vitória");
//        projectController.save(project);
//        
//        project.setId(2);
//        project.setName("Novo nome do projeto");
//        projectController.update(project);
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        projectController.removeById(3);
        
        projects.forEach((t) -> {
            System.out.println(t);
        });

        System.out.println("");
        
        TaskDAO taskController = new TaskDAO();

        Task task = new Task();
        task.setIdProject(1);
        task.setName("Teste Atualização");
        task.setDescription("Somente testando");
        task.setNotes("S Notas");
        task.setCompleted(false);
        task.setDeadline(new Date());
        task.setCreatedAt(new Date());
        task.setUpdateAt(new Date());
        
        //taskController.save(task);
        
        task.setId(4);
        String novoNome = "Novo teste";
        task.setName(novoNome);
        //taskController.update(task);

        List<Task> tasks = taskController.getAll(1);
        System.out.println("Total de tarefas = " + tasks.size());
        
        
        System.out.println("Tarefas do projeto do id 1 - Carreiras Policiais");
        tasks.forEach((t) -> {
            System.out.println(t);
        });
        
        //taskController.removeById(3);
    }
}
